title: Maputnik
email: me@lukasmartinelli.ch
description: Visual Map Editor for Mapbox GL
url: "http://maputnik.com"
markdown: kramdown
future: true
gems:
- jekyll-redirect-from
layout_themes:
  post: light
  posts: light

