title: Maputnik
email: me@lukasmartinelli.ch
description: Visual Map Editor for MapLibre Styles
baseurl: ""
url: "http://maputnik.github.io"
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title
plugins:
- jekyll-redirect-from
- kramdown-parser-gfm
layout_themes:
  post: light
  posts: light

