title: Maputnik
email: me@lukasmartinelli.ch
description: Visual Map Editor for Mapbox GL
url: "http://maputnik.com"
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title
gems:
- jekyll-redirect-from
layout_themes:
  post: light
  posts: light

